version: "3.9"

services:
  db:
    image: mariadb
    ports:
      - 3307:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Seoul
      MYSQL_USER: root
      MYSQL_PASSWORD: qwer1234
      MYSQL_DATABASE: eatUs
      MYSQL_ROOT_PASSWORD: 1234
    networks:
      - backend
    restart: always

networks:
  backend: